# Name of the pipeline
# Created by Luis Oviedo
name: $(Build.DefinitionName)

trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  pythonVersion: '3.9'

stages:
  - stage: Build
    displayName: 'Build and App Tests'
    jobs:
      - job: Build
        displayName: 'Build and Test'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '$(pythonVersion)'
              addToPath: true

          - script: |
              python -m venv venv
              source venv/bin/activate
              python -m pip install --upgrade pip
              pip install -r requirements.txt
              pip install pytest
              pip install pytest-cov              
            displayName: 'Install dependencies'

          - script: |
              source venv/bin/activate
              pytest --cov=./test --cov-report=xml --doctest-modules
            displayName: 'Run unit tests'
          - task: SnykSecurityScan@1
            inputs:
              serviceConnectionEndpoint: 'snyk'
              testType: 'code'
              failOnIssues: false            
            displayName: 'Snyk Code SecurityScan'
  - stage: BuildDockerImage
    displayName: 'Build Docker Image'
    jobs:
      - job: Docker
        displayName: 'Build and Store Docker Image'
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: 'python-fastapi'
              repository: 'luisog207/python-fastapi'
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'
            displayName: 'Docker build and Push'              
          - task: SnykSecurityScan@1
            inputs:
              serviceConnectionEndpoint: 'snyk'
              testType: 'container'
              dockerImageName: 'luisog207/python-fastapi'
              dockerfilePath: 'Dockerfile'
              monitorWhen: 'always'
              failOnIssues: false
            displayName: 'Snyk Test Container Image'
